using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace Kooboo.Sites.Payment.Methods.Square.lib.Models
{
    public class CreatePaymentRequest
    {
        public CreatePaymentRequest(string sourceId,
            string idempotencyKey,
            Models.Money amountMoney,
            Models.Money tipMoney = null,
            Models.Money appFeeMoney = null,
            bool? autocomplete = null,
            string orderId = null,
            string customerId = null,
            string locationId = null,
            string referenceId = null,
            string verificationToken = null,
            bool? acceptPartialAuthorization = null,
            string buyerEmailAddress = null,
            Models.Address billingAddress = null,
            Models.Address shippingAddress = null,
            string note = null,
            string statementDescriptionIdentifier = null)
        {
            SourceId = sourceId;
            IdempotencyKey = idempotencyKey;
            AmountMoney = amountMoney;
            TipMoney = tipMoney;
            AppFeeMoney = appFeeMoney;
            Autocomplete = autocomplete;
            OrderId = orderId;
            CustomerId = customerId;
            LocationId = locationId;
            ReferenceId = referenceId;
            VerificationToken = verificationToken;
            AcceptPartialAuthorization = acceptPartialAuthorization;
            BuyerEmailAddress = buyerEmailAddress;
            BillingAddress = billingAddress;
            ShippingAddress = shippingAddress;
            Note = note;
            StatementDescriptionIdentifier = statementDescriptionIdentifier;
        }

        /// <summary>
        /// The ID for the source of funds for this payment.  This can be a nonce
        /// generated by the Payment Form or a card on file made with the Customers API.
        /// </summary>
        [JsonProperty("source_id")]
        public string SourceId { get; }

        /// <summary>
        /// A unique string that identifies this CreatePayment request. Keys can be any valid string but
        /// must be unique for every CreatePayment request. 
        /// Max: 45 characters
        /// See [Idempotency keys](https://developer.squareup.com/docs/basics/api101/idempotency) for more information.
        /// </summary>
        [JsonProperty("idempotency_key")]
        public string IdempotencyKey { get; }

        /// <summary>
        /// Represents an amount of money. `Money` fields can be signed or unsigned.
        /// Fields that do not explicitly define whether they are signed or unsigned are
        /// considered unsigned and can only hold positive amounts. For signed fields, the
        /// sign of the value indicates the purpose of the money transfer. See
        /// [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
        /// for more information.
        /// </summary>
        [JsonProperty("amount_money")]
        public Models.Money AmountMoney { get; }

        /// <summary>
        /// Represents an amount of money. `Money` fields can be signed or unsigned.
        /// Fields that do not explicitly define whether they are signed or unsigned are
        /// considered unsigned and can only hold positive amounts. For signed fields, the
        /// sign of the value indicates the purpose of the money transfer. See
        /// [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
        /// for more information.
        /// </summary>
        [JsonProperty("tip_money")]
        public Models.Money TipMoney { get; }

        /// <summary>
        /// Represents an amount of money. `Money` fields can be signed or unsigned.
        /// Fields that do not explicitly define whether they are signed or unsigned are
        /// considered unsigned and can only hold positive amounts. For signed fields, the
        /// sign of the value indicates the purpose of the money transfer. See
        /// [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
        /// for more information.
        /// </summary>
        [JsonProperty("app_fee_money")]
        public Models.Money AppFeeMoney { get; }

        /// <summary>
        /// If set to `true`, this payment will be completed when possible. If
        /// set to `false`, this payment will be held in an approved state until either
        /// explicitly completed (captured) or canceled (voided). For more information, see 
        /// [Delayed Payments](https://developer.squareup.com/docs/payments-api/take-payments#delayed-payments).
        /// Default: true
        /// </summary>
        [JsonProperty("autocomplete")]
        public bool? Autocomplete { get; }

        /// <summary>
        /// Associate a previously created order with this payment
        /// </summary>
        [JsonProperty("order_id")]
        public string OrderId { get; }

        /// <summary>
        /// The ID of the customer associated with the payment.
        /// Required if the `source_id` refers to a card on file created using the
        /// Customers API.
        /// </summary>
        [JsonProperty("customer_id")]
        public string CustomerId { get; }

        /// <summary>
        /// The location ID to associate with the payment. If not specified, the default location is used.
        /// </summary>
        [JsonProperty("location_id")]
        public string LocationId { get; }

        /// <summary>
        /// A user-defined ID to associate with the payment.
        /// You can use this field to associate the payment to an entity in an external system.
        /// For example, you might specify an order ID that is generated by a third-party shopping cart.
        /// Limit 40 characters.
        /// </summary>
        [JsonProperty("reference_id")]
        public string ReferenceId { get; }

        /// <summary>
        /// An identifying token generated by `SqPaymentForm.verifyBuyer()`.
        /// Verification tokens encapsulate customer device information and 3-D Secure
        /// challenge results to indicate that Square has verified the buyer identity.
        /// See the [SCA Overview](https://developer.squareup.com/docs/sca-overview).
        /// </summary>
        [JsonProperty("verification_token")]
        public string VerificationToken { get; }

        /// <summary>
        /// If set to true and charging a Square Gift Card, a payment may be returned with
        /// amount_money equal to less than what was requested.  Example, a request for $20 when charging
        /// a Square Gift Card with balance of $5 wil result in an APPROVED payment of $5.  You may choose
        /// to prompt the buyer for an additional payment to cover the remainder, or cancel the gift card
        /// payment.  Cannot be `true` when `autocomplete = true`.
        /// For more information, see 
        /// [Partial amount with Square gift cards](https://developer.squareup.com/docs/payments-api/take-payments#partial-payment-gift-card).
        /// Default: false
        /// </summary>
        [JsonProperty("accept_partial_authorization")]
        public bool? AcceptPartialAuthorization { get; }

        /// <summary>
        /// The buyer's e-mail address
        /// </summary>
        [JsonProperty("buyer_email_address")]
        public string BuyerEmailAddress { get; }

        /// <summary>
        /// Represents a physical address.
        /// </summary>
        [JsonProperty("billing_address")]
        public Models.Address BillingAddress { get; }

        /// <summary>
        /// Represents a physical address.
        /// </summary>
        [JsonProperty("shipping_address")]
        public Models.Address ShippingAddress { get; }

        /// <summary>
        /// An optional note to be entered by the developer when creating a payment
        /// Limit 500 characters.
        /// </summary>
        [JsonProperty("note")]
        public string Note { get; }

        /// <summary>
        /// Optional additional payment information to include on the customer's card statement
        /// as part of statement description. This can be, for example, an invoice number, ticket number,
        /// or short description that uniquely identifies the purchase.
        /// Limit 20 characters.
        /// Note that the statement_description_identifier may get truncated on the statement description
        /// to fit the required information including the Square identifier (SQ *) and name of the
        /// merchant taking the payment.
        /// </summary>
        [JsonProperty("statement_description_identifier")]
        public string StatementDescriptionIdentifier { get; }
    }
}
