(function() {
    var controlTypeConfig = [{
        displayName: Kooboo.text.component.controlType.textBox,
        value: "TextBox",
        preview: "/_Admin/Images/ContentTypes/TextBox.png",
        dataType: "String"
    }, {
        displayName: Kooboo.text.component.controlType.textArea,
        value: "TextArea",
        preview: "/_Admin/Images/ContentTypes/textarea.png",
        dataType: "String"
    }, {
        displayName: Kooboo.text.component.controlType.wysiwygEditor,
        value: "Tinymce",
        preview: "/_Admin/Images/ContentTypes/tinymce.png",
        dataType: "String"
    }, {
        displayName: Kooboo.text.component.controlType.selection,
        value: "Selection",
        preview: "/_Admin/Images/ContentTypes/selection.png",
        dataType: "Undefined"
    }, {
        displayName: Kooboo.text.component.controlType.checkBox,
        value: "CheckBox",
        preview: "/_Admin/Images/ContentTypes/checkbox.png",
        dataType: "Undefined"
    }, {
        displayName: Kooboo.text.component.controlType.radioBox,
        value: "RadioBox",
        preview: "/_Admin/Images/ContentTypes/radiobox.png",
        dataType: "Undefined"
    }, {
        displayName: Kooboo.text.component.controlType.switch,
        value: "Switch",
        preview: "/_Admin/Images/ContentTypes/switch.png",
        dataType: "Bool"
    }, {
        displayName: Kooboo.text.component.controlType.mediaFile,
        value: "MediaFile",
        preview: "/_Admin/Images/ContentTypes/mediafiles.png",
        dataType: "Undefined"
    }, {
        displayName: Kooboo.text.component.controlType.dateTime,
        value: "DateTime",
        preview: "/_Admin/Images/ContentTypes/datetime.png",
        dataType: "DateTime"
    }, {
        displayName: Kooboo.text.component.controlType.number,
        value: "Number",
        preview: "/_Admin/Images/ContentTypes/TextBox.png",
        dataType: "Number"
    }];
    Kooboo.fieldEditor.controlTypeConfig = controlTypeConfig;
})()