//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kooboo.Lib.NUglify.Css {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CssStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CssStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kooboo.Lib.NUglify.Css.CssStrings", typeof(CssStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Color {0} can be collapsed to {1} 的本地化字符串。
        /// </summary>
        internal static string ColorCanBeCollapsed {
            get {
                return ResourceManager.GetString("ColorCanBeCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decimal point not followed by numeric digit 的本地化字符串。
        /// </summary>
        internal static string DecimalNoDigit {
            get {
                return ResourceManager.GetString("DecimalNoDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 declaration ignored 的本地化字符串。
        /// </summary>
        internal static string DeclarationIgnored {
            get {
                return ResourceManager.GetString("DeclarationIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1}) 的本地化字符串。
        /// </summary>
        internal static string DeclarationIgnoredFormat {
            get {
                return ResourceManager.GetString("DeclarationIgnoredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate namespace declaration; already declared &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string DuplicateNamespaceDeclaration {
            get {
                return ResourceManager.GetString("DuplicateNamespaceDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric value contains unnecessary characters: {0} is equivalent to {1}. 的本地化字符串。
        /// </summary>
        internal static string EquivalentNumbers {
            get {
                return ResourceManager.GetString("EquivalentNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected charset string, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedCharset {
            get {
                return ResourceManager.GetString("ExpectedCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected closing curly-brace, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedClosingBrace {
            get {
                return ResourceManager.GetString("ExpectedClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected closing bracket, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedClosingBracket {
            get {
                return ResourceManager.GetString("ExpectedClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected closing parenthesis, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedClosingParenthesis {
            get {
                return ResourceManager.GetString("ExpectedClosingParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected colon, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedColon {
            get {
                return ResourceManager.GetString("ExpectedColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expect comma, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedComma {
            get {
                return ResourceManager.GetString("ExpectedComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected comma or open brace, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedCommaOrOpenBrace {
            get {
                return ResourceManager.GetString("ExpectedCommaOrOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected comma or semi-colon, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedCommaOrSemicolon {
            get {
                return ResourceManager.GetString("ExpectedCommaOrSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected end of file; invalid input file 的本地化字符串。
        /// </summary>
        internal static string ExpectedEndOfFile {
            get {
                return ResourceManager.GetString("ExpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected equal sign, found {0} 的本地化字符串。
        /// </summary>
        internal static string ExpectedEqualSign {
            get {
                return ResourceManager.GetString("ExpectedEqualSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected expression, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedExpression {
            get {
                return ResourceManager.GetString("ExpectedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected function, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedFunction {
            get {
                return ResourceManager.GetString("ExpectedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected hex color, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedHexColor {
            get {
                return ResourceManager.GetString("ExpectedHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected identifier, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedIdentifier {
            get {
                return ResourceManager.GetString("ExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected identifier or string, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedIdentifierOrString {
            get {
                return ResourceManager.GetString("ExpectedIdentifierOrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected import string or uri, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedImport {
            get {
                return ResourceManager.GetString("ExpectedImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected media feature, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedMediaFeature {
            get {
                return ResourceManager.GetString("ExpectedMediaFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected media identifier, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedMediaIdentifier {
            get {
                return ResourceManager.GetString("ExpectedMediaIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected media query, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedMediaQuery {
            get {
                return ResourceManager.GetString("ExpectedMediaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected media-query expression, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedMediaQueryExpression {
            get {
                return ResourceManager.GetString("ExpectedMediaQueryExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected namespace string or uri, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedNamespace {
            get {
                return ResourceManager.GetString("ExpectedNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected number, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedNumber {
            get {
                return ResourceManager.GetString("ExpectedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected open brace, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedOpenBrace {
            get {
                return ResourceManager.GetString("ExpectedOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected opening parenthesis 的本地化字符串。
        /// </summary>
        internal static string ExpectedOpenParenthesis {
            get {
                return ResourceManager.GetString("ExpectedOpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected percentage, &apos;from&apos;, or &apos;to&apos;; found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedPercentageFromOrTo {
            get {
                return ResourceManager.GetString("ExpectedPercentageFromOrTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected calculation product, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedProduct {
            get {
                return ResourceManager.GetString("ExpectedProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected progid, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedProgId {
            get {
                return ResourceManager.GetString("ExpectedProgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected number or percentage value in rgb function, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedRgbNumberOrPercentage {
            get {
                return ResourceManager.GetString("ExpectedRgbNumberOrPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected selector, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedSelector {
            get {
                return ResourceManager.GetString("ExpectedSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected semi-colon, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedSemicolon {
            get {
                return ResourceManager.GetString("ExpectedSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected semicolon or closing curly-brace, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedSemicolonOrClosingBrace {
            get {
                return ResourceManager.GetString("ExpectedSemicolonOrClosingBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected semi-colon or close brace, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedSemicolonOrOpenBrace {
            get {
                return ResourceManager.GetString("ExpectedSemicolonOrOpenBrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected calculation sum, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedSum {
            get {
                return ResourceManager.GetString("ExpectedSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected term, found {0} 的本地化字符串。
        /// </summary>
        internal static string ExpectedTerm {
            get {
                return ResourceManager.GetString("ExpectedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected calculation unit, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExpectedUnit {
            get {
                return ResourceManager.GetString("ExpectedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JavaScript error in expression property: {0} 的本地化字符串。
        /// </summary>
        internal static string ExpressionError {
            get {
                return ResourceManager.GetString("ExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser hack generates invalid CSS 的本地化字符串。
        /// </summary>
        internal static string HackGeneratesInvalidCss {
            get {
                return ResourceManager.GetString("HackGeneratesInvalidCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash ({0}) not allowed after unary operator 的本地化字符串。
        /// </summary>
        internal static string HashAfterUnaryNotAllowed {
            get {
                return ResourceManager.GetString("HashAfterUnaryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicode high-surrogate value (0x{0:x}) not immediately followed by unicode-escaped low-surrogate value 的本地化字符串。
        /// </summary>
        internal static string HighSurrogateNoLow {
            get {
                return ResourceManager.GetString("HighSurrogateNoLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicode high-surrogate value (0x{0:x}) followed by invalid low-surrogate value: 0x{1:x} 的本地化字符串。
        /// </summary>
        internal static string InvalidLowSurrogate {
            get {
                return ResourceManager.GetString("InvalidLowSurrogate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Unicode Range Token: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidUnicodeRange {
            get {
                return ResourceManager.GetString("InvalidUnicodeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media queries require a space between &apos;and&apos; and the opening parenthesis: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string MediaQueryRequiresSpace {
            get {
                return ResourceManager.GetString("MediaQueryRequiresSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parser 的本地化字符串。
        /// </summary>
        internal static string ParserSubsystem {
            get {
                return ResourceManager.GetString("ParserSubsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Byte-order mark at front of source indicates possible encoding issue. 的本地化字符串。
        /// </summary>
        internal static string PossibleCharsetError {
            get {
                return ResourceManager.GetString("PossibleCharsetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Possible cross-browser invalid class name: {0} 的本地化字符串。
        /// </summary>
        internal static string PossibleInvalidClassName {
            get {
                return ResourceManager.GetString("PossibleInvalidClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;progid:&apos; is an IE-only construct that generates invalid CSS 的本地化字符串。
        /// </summary>
        internal static string ProgIdIEOnly {
            get {
                return ResourceManager.GetString("ProgIdIEOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scanner 的本地化字符串。
        /// </summary>
        internal static string ScannerSubsystem {
            get {
                return ResourceManager.GetString("ScannerSubsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token not allowed after unary operator: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string TokenAfterUnaryNotAllowed {
            get {
                return ResourceManager.GetString("TokenAfterUnaryNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Namespace used but not declared in a @namespace statement: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UndeclaredNamespace {
            get {
                return ResourceManager.GetString("UndeclaredNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An underscore is not a valid CSS1 or CSS2 identifier character 的本地化字符串。
        /// </summary>
        internal static string UnderscoreNotValid {
            get {
                return ResourceManager.GetString("UnderscoreNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected at-keyword, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedAtKeyword {
            get {
                return ResourceManager.GetString("UnexpectedAtKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @charset must be very first token in file 的本地化字符串。
        /// </summary>
        internal static string UnexpectedCharset {
            get {
                return ResourceManager.GetString("UnexpectedCharset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected dimension: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedDimension {
            get {
                return ResourceManager.GetString("UnexpectedDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected end of file encountered 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEndOfFile {
            get {
                return ResourceManager.GetString("UnexpectedEndOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected escape sequence: \{0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedEscape {
            get {
                return ResourceManager.GetString("UnexpectedEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected function; only calc( or attr( allowed here, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedFunction {
            get {
                return ResourceManager.GetString("UnexpectedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected number character: {0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedNumberCharacter {
            get {
                return ResourceManager.GetString("UnexpectedNumberCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected string character: {0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedStringCharacter {
            get {
                return ResourceManager.GetString("UnexpectedStringCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected token, found &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ? 的本地化字符串。
        /// </summary>
        internal static string UnknownCharacterEncoding {
            get {
                return ResourceManager.GetString("UnknownCharacterEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown error 的本地化字符串。
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unnecessary units on a value of zero 的本地化字符串。
        /// </summary>
        internal static string UnnecessaryUnits {
            get {
                return ResourceManager.GetString("UnnecessaryUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated comment. 的本地化字符串。
        /// </summary>
        internal static string UnterminatedComment {
            get {
                return ResourceManager.GetString("UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unterminated string: {0} 的本地化字符串。
        /// </summary>
        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
    }
}
