import type { SocialItem } from ".";

export const icons: Record<string, SocialItem[]> = {
  follow: [
    {
      id: "facebook",
      name: "facebook",
      url: "https://www.facebook.com/",
      title: "Facebook",
      alternateText: "Facebook",
      type: "follow",
      icon: "facebook@2x.png",
    },
    {
      id: "twitter",
      name: "twitter",
      url: "https://twitter.com/",
      title: "Twitter",
      alternateText: "Twitter",
      type: "follow",
      icon: "twitter@2x.png",
    },
    {
      id: "linkedin",
      name: "linkedin",
      url: "https://www.linkedin.com/",
      title: "LinkedIn",
      alternateText: "LinkedIn",
      type: "follow",
      icon: "linkedin@2x.png",
    },
    {
      id: "youtube",
      name: "youtube",
      url: "https://www.youtube.com/",
      title: "YouTube",
      alternateText: "YouTube",
      type: "follow",
      icon: "youtube@2x.png",
    },
    {
      id: "pinterest",
      name: "pinterest",
      url: "https://www.pinterest.com/",
      title: "Pinterest",
      alternateText: "Pinterest",
      type: "follow",
      icon: "pinterest@2x.png",
    },
    {
      id: "instagram",
      name: "instagram",
      url: "https://instagram.com/",
      title: "Instagram",
      alternateText: "Instagram",
      type: "follow",
      icon: "instagram@2x.png",
    },
    {
      id: "Vkontakte",
      name: "Vkontakte",
      url: "https://vk.com",
      title: "Vkontakte",
      alternateText: "Vkontakte",
      type: "follow",
      icon: "vkontakte@2x.png",
    },
    {
      id: "Odnoklassniki",
      name: "Odnoklassniki",
      url: "https://ok.ru",
      title: "Odnoklassniki",
      alternateText: "Odnoklassniki",
      type: "follow",
      icon: "odnoklassniki@2x.png",
    },
    {
      id: "Blogger",
      name: "Blogger",
      url: "https://www.blogger.com/follow-blog.g?blogID=",
      title: "Blogger",
      alternateText: "Blogger",
      type: "follow",
      icon: "blogger@2x.png",
    },
    {
      id: "Medium",
      name: "Medium",
      url: "https://medium.com",
      title: "Medium",
      alternateText: "Medium",
      type: "follow",
      icon: "medium@2x.png",
    },
    {
      id: "Tumblr",
      name: "Tumblr",
      url: "https://www.tumblr.com/follow/",
      title: "Tumblr",
      alternateText: "Tumblr",
      type: "follow",
      icon: "tumblr@2x.png",
    },
    {
      id: "SoundCloud",
      name: "SoundCloud",
      url: "https://soundcloud.com",
      title: "SoundCloud",
      alternateText: "SoundCloud",
      type: "follow",
      icon: "soundcloud@2x.png",
    },
    {
      id: "Spotify",
      name: "Spotify",
      url: "https://open.spotify.com",
      title: "Spotify",
      alternateText: "Spotify",
      type: "follow",
      icon: "spotify@2x.png",
    },
    {
      id: "Vimeo",
      name: "Vimeo",
      url: "https://vimeo.com",
      title: "Vimeo",
      alternateText: "Vimeo",
      type: "follow",
      icon: "vimeo@2x.png",
    },
    {
      id: "Vine",
      name: "Vine",
      url: "https://vine.co",
      title: "Vine",
      alternateText: "Vine",
      type: "follow",
      icon: "vine@2x.png",
    },
    {
      id: "SinaWeibo",
      name: "SinaWeibo",
      url: "http://www.weibo.com",
      title: "SinaWeibo",
      alternateText: "SinaWeibo",
      type: "follow",
      icon: "sina-weibo@2x.png",
    },
    {
      id: "Glassdoor",
      name: "Glassdoor",
      url: "https://www.glassdoor.com",
      title: "Glassdoor",
      alternateText: "Glassdoor",
      type: "follow",
      icon: "glassdoor@2x.png",
    },
    {
      id: "Snapchat",
      name: "Snapchat",
      url: "https://www.snapchat.com",
      title: "Snapchat",
      alternateText: "Snapchat",
      type: "follow",
      icon: "snapchat@2x.png",
    },
    {
      id: "Telegram",
      name: "Telegram",
      url: "https://telegram.org",
      title: "Telegram",
      alternateText: "Telegram",
      type: "follow",
      icon: "telegram@2x.png",
    },
    {
      id: "Wechat",
      name: "Wechat",
      url: "https://www.wechat.com",
      title: "Wechat",
      alternateText: "Wechat",
      type: "follow",
      icon: "wechat@2x.png",
    },
    {
      id: "TikTok",
      name: "TikTok",
      url: "https://www.tiktok.com",
      title: "TikTok",
      alternateText: "TikTok",
      type: "follow",
      icon: "tiktok@2x.png",
    },
    {
      id: "Tripadvisor",
      name: "Tripadvisor",
      url: "https://www.tripadvisor.com",
      title: "Tripadvisor",
      alternateText: "Tripadvisor",
      type: "follow",
      icon: "tripadvisor@2x.png",
    },
    {
      id: "WhatsApp",
      name: "WhatsApp",
      url: "https://www.whatsapp.com",
      title: "WhatsApp",
      alternateText: "WhatsApp",
      type: "follow",
      icon: "whatsapp@2x.png",
    },
  ],
  share: [
    {
      id: "facebook",
      name: "facebook",
      url: "[ShareOn]",
      title: "Facebook",
      alternateText: "Facebook",
      type: "share",
      icon: "facebook@2x.png",
      prefix: "https://www.facebook.com/sharer.php?u=",
    },
    {
      id: "twitter",
      name: "twitter",
      url: "[ShareOn]",
      title: "Twitter",
      alternateText: "Twitter",
      type: "share",
      icon: "twitter@2x.png",
      prefix: "https://twitter.com/intent/tweet?url=",
    },
    {
      id: "linkedin",
      name: "linkedin",
      url: "[ShareOn]",
      title: "LinkedIn",
      alternateText: "LinkedIn",
      type: "share",
      icon: "linkedin@2x.png",
      prefix: "https://www.linkedin.com/shareArticle?mini=true&url=",
    },
    {
      id: "Vkontakte",
      name: "Vkontakte",
      url: "[ShareOn]",
      title: "Vkontakte",
      alternateText: "Vkontakte",
      type: "share",
      icon: "vkontakte@2x.png",
      prefix: "https://vk.com/share.php?url=",
    },
    {
      id: "Odnoklassniki",
      name: "Odnoklassniki",
      url: "[ShareOn]",
      title: "Odnoklassniki",
      alternateText: "Odnoklassniki",
      type: "share",
      icon: "odnoklassniki@2x.png",
      prefix:
        "https://www.odnoklassniki.ru/dk?st.cmd=addShare&st.s=1&st._surl=",
    },
    {
      id: "qZone",
      name: "qZone",
      url: "[ShareOn]",
      title: "qZone",
      alternateText: "qZone",
      type: "share",
      icon: "qzone@2x.png",
      prefix: "http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=",
    },
    {
      id: "SinaWeibo",
      name: "SinaWeibo",
      url: "[ShareOn]",
      title: "SinaWeibo",
      alternateText: "SinaWeibo",
      type: "share",
      icon: "sina-weibo@2x.png",
      prefix: "http://service.weibo.com/share/share.php?url=",
    },
  ],
  others: [
    {
      id: "Web Site",
      name: "Web Site",
      url: "",
      title: "Web Site",
      alternateText: "Web Site",
      type: "others",
      icon: "website@2x.png",
      prefix: "",
    },
    {
      id: "E-Mail",
      name: "E-Mail",
      url: "",
      title: "E-Mail",
      alternateText: "E-Mail",
      type: "others",
      icon: "mail@2x.png",
      prefix: "mailto:",
    },
    {
      id: "phone",
      name: "Phone",
      url: "",
      title: "Call phone number",
      alternateText: "Phone",
      type: "others",
      icon: "phone@2x.png",
      prefix: "tel:",
    },
  ],
};
