let kbLang = localStorage.getItem("lang");
if (!kbLang) kbLang = "en";
export const lang = kbLang;

const en = {
  MENU: "Menu",
  EDIT: "Edit",
  COPY: "Copy",
  DELETE: "Delete",
  EDIT_IMAGE: "Edit image",
  EDIT_LINK: "Edit link",
  EDIT_IMAGES: "Edit images",
  EDIT_LINKS: "Edit links",
  ENTER_LINK: "Enter link",
  EDIT_HTML_BLOCK: "Edit html block",
  OK: "Ok",
  CANCEL: "Cancel",
  PAGE_LINK: "Page link",
  OUT_LINK: " Out link",
  EDIT_REPEAT: "Edit repeat item",
  EDIT_MENU: "Edit menu",
  EDIT_STYLE: "Edit style",
  ALT: "Alt",
  TITLE: "Title",
  WIDTH: "Width",
  HEIGHT: "Height",
  PLEASE_EDIT_AFTER_SAVE: "Please edit after save",
  COPY_REPEAT: "Copy repeat item",
  DELETE_REPEAR: "Delete repeat item",
  REPLACE_TO_IMG: "Replace to image",
  REPLACE_TO_TEXT: "Replace to Text",
  MOVE: "Move",
  PREVIOUS: "Undo",
  NEXT: "Redo",
  SAVE: "Save",
  CONTENT_IMAGES: "Content images",
  STYLE_IMAGES: "Style images",
  DOM_IMAGES: "DOM images",
  CONTENT_LINKS: "Content links",
  DOM_LINKS: "DOM links",
  BACKGROUND_IMAGE: "Background image",
  COLOR: "Color",
  BACKGROUND_COLOR: "Background color",
  FONT: "Font",
  FONT_SIZE: "Font size",
  FONT_WEIGHT: "Font weight",
  FONT_FAMILY: "Font family",
  SIZE: "Size",
  CLICK: "Click",
  EDIT_FORM: "Edit form",
  EXPAND_SELECTION: "Expand selection"
};

const zh = {
  MENU: "菜单",
  EDIT: "编辑",
  COPY: "复制这块",
  DELETE: "删除",
  EDIT_IMAGE: "编辑图片",
  EDIT_LINK: "编辑链接",
  EDIT_IMAGES: "编辑图片",
  EDIT_LINKS: "编辑链接",
  ENTER_LINK: "跳转链接",
  EDIT_HTML_BLOCK: "编辑HTML代码块",
  CANCEL: "取消",
  OK: "确定",
  PAGE_LINK: "页面链接",
  OUT_LINK: "外部链接",
  EDIT_REPEAT: "编辑项目",
  EDIT_MENU: "编辑菜单",
  EDIT_STYLE: "编辑样式",
  ALT: "替代文本",
  HEIGHT: "高度",
  TITLE: "标题",
  WIDTH: "宽度",
  PLEASE_EDIT_AFTER_SAVE: "请保存后再编辑",
  COPY_REPEAT: "复制项目",
  DELETE_REPEAR: "删除项目",
  REPLACE_TO_IMG: "替换为图片",
  REPLACE_TO_TEXT: "替换为文字",
  MOVE: "移动",
  NEXT: "下一步",
  PREVIOUS: "上一步",
  SAVE: "保存",
  CONTENT_IMAGES: "内容图片",
  STYLE_IMAGES: "样式图片",
  DOM_IMAGES: "DOM 图片",
  CONTENT_LINKS: "内容链接",
  DOM_LINKS: "DOM 链接",
  BACKGROUND_COLOR: "背景颜色",
  BACKGROUND_IMAGE: "背景图片",
  COLOR: "颜色",
  FONT: "字体",
  FONT_FAMILY: "字体风格",
  FONT_SIZE: "字体大小",
  FONT_WEIGHT: "字体重量",
  SIZE: "大小",
  CLICK: "点击",
  EDIT_FORM: "编辑表单",
  EXPAND_SELECTION: "扩大选区"
} as typeof en;

var langPackages = { en, zh };
export const TEXT = langPackages[lang as keyof typeof langPackages] as typeof en;
