let kbLang = localStorage.getItem("lang");
if (!kbLang) kbLang = "en";
export const lang = kbLang;
const Kooboo = (parent as any).Kooboo;

export const TEXT = {
  MENU: Kooboo.text.common.Menu,
  EDIT: Kooboo.text.common.edit,
  COPY: Kooboo.text.inlineEditor.Copy,
  DELETE: Kooboo.text.common.delete,
  EDIT_IMAGE: Kooboo.text.inlineEditor.editImage,
  EDIT_LINK: Kooboo.text.inlineEditor.editLink,
  EDIT_IMAGES: Kooboo.text.inlineEditor.editImages,
  EDIT_LINKS: Kooboo.text.inlineEditor.editLinks,
  ENTER_LINK: Kooboo.text.inlineEditor.enterLink,
  EDIT_HTML_BLOCK: Kooboo.text.inlineEditor.editHtmlblock,
  OK: Kooboo.text.common.OK,
  CANCEL: Kooboo.text.common.cancel,
  PAGE_LINK: Kooboo.text.inlineEditor.pageLink,
  OUT_LINK: Kooboo.text.inlineEditor.outLink,
  EDIT_REPEAT: Kooboo.text.inlineEditor.editRepeaterItem,
  EDIT_MENU: Kooboo.text.inlineEditor.editMenu,
  EDIT_STYLE: Kooboo.text.inlineEditor.editStyle,
  ALT: "Alt ",
  TITLE: "Title ",
  WIDTH: Kooboo.text.inlineEditor.width,
  HEIGHT: Kooboo.text.inlineEditor.height,
  PLEASE_EDIT_AFTER_SAVE: Kooboo.text.inlineEditor.editAfter,
  COPY_REPEAT: Kooboo.text.inlineEditor.copyRepeaterItem,
  DELETE_REPEAR: Kooboo.text.inlineEditor.removeRepeaterItem,
  REPLACE_TO_IMG: Kooboo.text.inlineEditor.replacewithImage,
  REPLACE_TO_TEXT: Kooboo.text.inlineEditor.replacewithText,
  MOVE: Kooboo.text.inlineEditor.move,
  PREVIOUS: Kooboo.text.inlineEditor.undo,
  NEXT: Kooboo.text.inlineEditor.redo,
  SAVE: Kooboo.text.common.save,
  CONTENT_IMAGES: Kooboo.text.inlineEditor.contentImages,
  STYLE_IMAGES: Kooboo.text.inlineEditor.styleImages,
  DOM_IMAGES: Kooboo.text.inlineEditor.domImages,
  CONTENT_LINKS: Kooboo.text.inlineEditor.contentLinks,
  DOM_LINKS: Kooboo.text.inlineEditor.domLinks,
  BACKGROUND_IMAGE: Kooboo.text.inlineEditor.backgroundImage,
  COLOR: Kooboo.text.inlineEditor.color,
  BACKGROUND_COLOR: Kooboo.text.inlineEditor.backgroundColor,
  FONT: Kooboo.text.inlineEditor.font,
  FONT_SIZE: Kooboo.text.inlineEditor.fontSize,
  FONT_WEIGHT: Kooboo.text.inlineEditor.fontWeight,
  FONT_FAMILY: Kooboo.text.inlineEditor.fontFamily,
  SIZE: Kooboo.text.common.size,
  CLICK: Kooboo.text.inlineEditor.click,
  EXPAND_SELECTION: Kooboo.text.inlineEditor.expandSelection,
  GLOBAL_UPDATE: Kooboo.text.inlineEditor.globalUpdate,
  EDIT_COLOR: Kooboo.text.inlineEditor.editColor,
  EDIT_DATA: Kooboo.text.inlineEditor.editData,
  HTML_MODE_TIP: Kooboo.text.inlineEditor.htmlModeTip,
  CLICK_REPLACE: Kooboo.text.inlineEditor.clickReplace
};
