let kbLang = localStorage.getItem("lang");
if (!kbLang) kbLang = "en";
export const lang = kbLang;

const en = {
  MENU: "menu",
  EDIT: "edit",
  COPY: "copy",
  DELETE: "delete",
  EDIT_IMAGE: "edit image",
  EDIT_LINK: "edit link",
  JUMP_LINK: "jump link",
  EDIT_HTML_BLOCK: "edit html blick",
  OK: "ok",
  CANCEL: "cancel",
  PAGE_LINK: "page link",
  OUT_LINK: " out lint",
  EDIT_REPEAT: "edit repeat item",
  EDIT_MENU: "edit menu",
  EDIT_STYLE: "edit style",
  ALT: "alt",
  TITLE: "title",
  WIDTH: "width",
  HEIGHT: "height",
  PLEASE_EDIT_AFTER_SAVE: "please edit after save",
  COPY_REPEAT: "copy repeat item",
  DELETE_REPEAR: "delete repeat item",
  REPLACE_TO_IMG: "replace to image",
  REPLACE_TO_TEXT: "replace to Text",
  MOVE: "move",
  PREVIOUS: "previous",
  NEXT: "next",
  SAVE: "save",
  CONTENT_IMAGE: "content image",
  STYLE_IMAGE: "style image",
  DOM_IMAGE: "DOM image",
  CONTENT_LINK: "content link",
  DOM_LINK: "DOM link"
};

const zh = {
  MENU: "菜单",
  EDIT: "编辑",
  COPY: "复制这块",
  DELETE: "删除",
  EDIT_IMAGE: "编辑图片",
  EDIT_LINK: "编辑链接",
  JUMP_LINK: "跳转链接",
  EDIT_HTML_BLOCK: "编辑HTML代码块",
  CANCEL: "取消",
  OK: "确定",
  PAGE_LINK: "页面链接",
  OUT_LINK: "外部链接",
  EDIT_REPEAT: "编辑项目",
  EDIT_MENU: "编辑菜单",
  EDIT_STYLE: "编辑样式",
  ALT: "替代文本",
  HEIGHT: "高度",
  TITLE: "标题",
  WIDTH: "宽度",
  PLEASE_EDIT_AFTER_SAVE: "请保存后再编辑",
  COPY_REPEAT: "复制项目",
  DELETE_REPEAR: "删除项目",
  REPLACE_TO_IMG: "替换为图片",
  REPLACE_TO_TEXT: "替换为文字",
  MOVE: "移动",
  NEXT: "下一步",
  PREVIOUS: "上一步",
  SAVE: "保存",
  CONTENT_IMAGE: "内容图片",
  STYLE_IMAGE: "样式图片",
  DOM_IMAGE: "DOM 图片",
  CONTENT_LINK: "内容链接",
  DOM_LINK: "DOM 链接"
} as typeof en;

var langPackages = { en, zh };
export const TEXT = langPackages[lang as keyof typeof langPackages] as typeof en;
