using System;
using System.Collections.Generic;
using System.Text;

namespace Kooboo.Sites.SMS.ChinaMobile.Models
{
    public class NotificationSubmitResponse
    {
        /// <summary>
        /// Response status
        /// </summary>
        public string Rspcod { get; set; }

        /// <summary>
        /// Message group id, generated by CMCC Cloud MAS
        /// </summary>
        public string MgsGroup { get; set; }

        /// <summary>
        /// Success flag for the validation
        /// </summary>
        public bool Success { get; set; }
    }

    public enum ResponseCodes
    {
        /// <summary>
        /// Mac validation failed
        /// </summary>
        IllegalMac,

        /// <summary>
        /// Invalid signature
        /// </summary>
        IllegalSignId,

        /// <summary>
        /// Invalid message
        /// </summary>
        InvalidMessage,

        /// <summary>
        /// Invalid username/password
        /// </summary>
        InvalidUsrOrPwd,

        /// <summary>
        /// Signature not found
        /// </summary>
        NoSignId,

        /// <summary>
        /// Success
        /// </summary>
        Success,

        /// <summary>
        /// Phonenumber amount should be less than (or equal to) 5000
        /// </summary>
        TooManyMobiles
    }
}
