export enum ModuleConstants {
  Style = "Style",
  Script = "Script",
  ResourceGroup = "ResourceGroup",
  Layout = "Layout",
  Form = "Form",
  Menu = "Menu",
  Authentication = "Authentication",
  View = "View",
  Route = "route",
  Component = "Component",
  Code = "Code",
  Page = "Page",
  Media = "Media",
  Image = "Image",
  File = "File",
  ContentType = "ContentType",
  Domain = "Domain",
  Database = "Database",
  ContentFolder = "ContentFolder",
  KeyValue = "KeyValue",
  Site = "Site",
  Role = "Role",
  KConfig = "KConfig",
}
