(function() {
    Kooboo.columnEditor.controlTypes = [{
        displayName: Kooboo.text.component.controlType.textBox,
        value: "TextBox",
        dataType: "String"
    }, {
        displayName: Kooboo.text.component.controlType.textArea,
        value: "TextArea",
        dataType: "String"
    }, {
        displayName: Kooboo.text.component.controlType.wysiwygEditor,
        value: "Tinymce",
        dataType: "String"
    }, {
        displayName: Kooboo.text.component.controlType.selection,
        value: "Selection",
        dataType: "Undefined"
    }, {
        displayName: Kooboo.text.component.controlType.checkBox,
        value: "CheckBox",
        dataType: "Undefined"
    }, {
        displayName: Kooboo.text.component.controlType.radioBox,
        value: "RadioBox",
        dataType: "Undefined"
    }, {
        displayName: Kooboo.text.component.controlType.boolean,
        value: "Boolean",
        dataType: "Bool"
    }, {
        displayName: Kooboo.text.component.controlType.dateTime,
        value: "DateTime",
        dataType: "DateTime"
    }, {
        displayName: Kooboo.text.component.controlType.number,
        value: "Number",
        dataType: "Number"
    }]
})()